# Generated by Django 6.1 on 2026-08-25 04:50

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/amruth/Downloads/pro/django/dam/private_media')), upload_to='gallery/%Y/%m/'),
        ),
    ]
